const foods = [
  {
    id: 1,
    title: "Misto-quente",
    image: "https://images.pexels.com/photos/15228654/pexels-photo-15228654/free-photo-of-cooked-food-on-white-ceramic-plate.jpeg",
    description: "Pão francês na chapa, recheado com mortadela e queijo",
    price: 7,
  },
  {
    id: 2,
    title: "Cachorro-Quente",
    image: "https://images.pexels.com/photos/3023479/pexels-photo-3023479.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "Pão macio com salsicha, ketchup e mostarda",
    price: 7,
  },
  {
    id: 3,
    title: "Tapioca com carne seca",
    image: "https://images.pexels.com/photos/11094180/pexels-photo-11094180.jpeg",
    description: "Tapioca recheada com carne seca bovina desfiada, tomate e queijo",
    price: 10.00,
  },
  {
    id: 4,
    title: "Sanduíche Natural de Atum",
    image: "https://images.pexels.com/photos/30910213/pexels-photo-30910213/free-photo-of-fresh-tuna-sandwich-with-iced-tea-on-rustic-table.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "Pão integral, atum, maionese, alface e tomate",
    price: 14.00,
  },
  {
    id: 5,
    title: "Batata Frita",
    image: "https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "Porção de batatas fritas crocantes e bem temperadas",
    price: 12.00,
  },
  {
    id: 6,
    title: "Pastel de Carne",
    image: "https://images.pexels.com/photos/24962986/pexels-photo-24962986/free-photo-of-close-up-of-pastel-frying-in-a-pan.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "Pastel frito recheado com carne moída bem temperada",
    price: 7.00,
  },
  {
    id: 7,
    title: "Milkshake de Ovomaltine",
    image: "https://images.pexels.com/photos/5527544/pexels-photo-5527544.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "Milkshake cremoso com crocante de Ovomaltine e chantilly",
    price: 14.50,
  },
  {
    id: 8,
    title: "Açaí com Granola",
    image: "https://images.pexels.com/photos/8465241/pexels-photo-8465241.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "Tigela de açaí com granola e leite condensado",
    price: 16.00,
  },
  {
    id: 9,
    title: "Refrigerante Lata",
    image: "https://images.pexels.com/photos/104509/pexels-photo-104509.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "Refrigerante gelado (Coca-Cola, Guaraná, Fanta, etc.)",
    price: 7.00,
  },
  {
    id: 10,
    title: "Pão de Queijo Recheado",
    image: "https://images.pexels.com/photos/20450299/pexels-photo-20450299/free-photo-of-brazilian-cheese-bread-in-the-oven.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "Pão de queijo grande recheado com requeijão cremoso",
    price: 8.50,
  },
  {
    id: 11,
    title: "Misto-quente",
    image: "https://images.pexels.com/photos/15228654/pexels-photo-15228654/free-photo-of-cooked-food-on-white-ceramic-plate.jpeg",
    description: "Pão francês na chapa, recheado com mortadela e queijo",
    price: 7,
  },
  {
    id: 12,
    title: "Cachorro-Quente",
    image: "https://images.pexels.com/photos/3023479/pexels-photo-3023479.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "Pão macio com salsicha, ketchup e mostarda",
    price: 7,
  },
  {
    id: 13,
    title: "Tapioca com carne seca",
    image: "https://images.pexels.com/photos/11094180/pexels-photo-11094180.jpeg",
    description: "Tapioca recheada com carne seca bovina desfiada, tomate e queijo",
    price: 10.00,
  },
  {
    id: 14,
    title: "Sanduíche Natural de Atum",
    image: "https://images.pexels.com/photos/30910213/pexels-photo-30910213/free-photo-of-fresh-tuna-sandwich-with-iced-tea-on-rustic-table.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "Pão integral, atum, maionese, alface e tomate",
    price: 14.00,
  },
  {
    id: 15,
    title: "Batata Frita",
    image: "https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "Porção de batatas fritas crocantes e bem temperadas",
    price: 12.00,
  },
  {
    id: 16,
    title: "Pastel de Carne",
    image: "https://images.pexels.com/photos/24962986/pexels-photo-24962986/free-photo-of-close-up-of-pastel-frying-in-a-pan.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "Pastel frito recheado com carne moída bem temperada",
    price: 7.00,
  },
  {
    id: 17,
    title: "Milkshake de Ovomaltine",
    image: "https://images.pexels.com/photos/5527544/pexels-photo-5527544.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "Milkshake cremoso com crocante de Ovomaltine e chantilly",
    price: 14.50,
  },
  {
    id: 18,
    title: "Açaí com Granola",
    image: "https://images.pexels.com/photos/8465241/pexels-photo-8465241.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "Tigela de açaí com granola e leite condensado",
    price: 16.00,
  },
  {
    id: 19,
    title: "Refrigerante Lata",
    image: "https://images.pexels.com/photos/104509/pexels-photo-104509.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "Refrigerante gelado (Coca-Cola, Guaraná, Fanta, etc.)",
    price: 7.00,
  },
  {
    id: 20,
    title: "Pão de Queijo Recheado",
    image: "https://images.pexels.com/photos/20450299/pexels-photo-20450299/free-photo-of-brazilian-cheese-bread-in-the-oven.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    description: "Pão de queijo grande recheado com requeijão cremoso",
    price: 8.50,
  }
];

export default foods;